# Generated by Django 3.1 on 2020-08-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imagesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_type', models.CharField(choices=[('home', 'home'), ('office', 'office')], max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('cover_image', models.ImageField(upload_to='images/')),
                ('design_image', models.ManyToManyField(to='imagesapp.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cover_image', models.ImageField(upload_to='images/')),
                ('concept_image', models.ManyToManyField(to='imagesapp.Image')),
                ('concept_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='display.conceptcategory')),
            ],
        ),
    ]
