# Generated by Django 3.1 on 2020-08-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concept',
            old_name='cover_image',
            new_name='concept_cover_image',
        ),
        migrations.AlterField(
            model_name='concept',
            name='concept_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.conceptcategory'),
        ),
        migrations.AlterField(
            model_name='conceptcategory',
            name='info',
            field=models.TextField(blank=True, default='Some info here.'),
        ),
    ]
