# Generated by Django 3.1 on 2020-12-05 15:58

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200829_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='quote',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
